### ISSUE TITLE
registerReceiver only for the running app?

### ISSUE THREAD

**Issue by pke** [jgkiano/react-native-android-sms-verification-api#8]
Is it possible to register the receiver to only get it access to SMS intended for the app specified in the SMS (hash)?

**Comment by jgkiano** [comment]
not sure i understand, maybe explain with a use-case? but if you are using the app hash the you should be using the SMS Retriever API which won't require any "Allow <my_app> to read message" permission so the os will route the SMS directly to the app so no other messages will be accessed. 

consent api due to the nature of not having a hash there's a probability the SMS coming in isn't the otp that's why user is asked to give consent after verifying its the OTP message.

**Comment by pke** [comment]
I was referring to the `RECEIVER_NOT_EXORTED` flag instead of `RECEIVER_EXPORTED` as discussed here: https://stackoverflow.com/a/77276774/299209

But now sure how relevant it is?

**Comment by jgkiano** [comment]
From the [docs](https://developers.google.com/identity/sms-retriever/request), they show case the receiver being exported (although registered statically). I assume they would want us to use the `RECEIVER_EXPORTED` flag when registering dynamically.

**Comment by pke** [comment]
Understood. I have tested that when the SMS does not contain the hash, the app will not get access to it. So I'll close this as its working as designed. Thanks!
